name: Sync to Hugging Face Space

# L'action parte sul push nel main
on:
  push:
    branches: [main]
  workflow_dispatch: # permette di farlo partire anche a mano se serve

# 2. COSA DEVE FARE?
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest # Gli diamo un computer Linux virtuale su cui lavorare
    steps:
      - uses: actions/checkout@v3 # Scarica il tuo codice da GitHub
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }} # Prende la chiave dalla tua cassaforte
        run: |
          git remote add space https://user:$HF_TOKEN@huggingface.co/spaces/TUO_USERNAME_HF/NOME_DEL_TUO_SPACE
          git push --force space main